spring:
  application:
    name: telegram
  config:
    import: optional:configserver:http://localhost:8888

  # DEFAULT CONFIGURATION FOR STARTUP WITHOUT CONFIG SERVER
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ens
    username: postgres
    password: 1234
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
application:
  title: telegram
  version: 0.1
  config:
    security-tg-users:
      url: http://localhost:8080/api/security-tg-users
server:
  port: 8094

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    app:
      sender: trace