server:
  port: 8888

application:
  title: config
  version: 0.1

spring:
  profiles:
    active: native
  application:
    name: config
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations

logging:
  level:
    app: trace
  file:
    path: \logs\
    name: config.log