FROM maven:3.9.6-eclipse-temurin-17-alpine AS build

WORKDIR /app/module

#parent pom.xml
COPY ../pom.xml ../

#utils pom.xml and src
COPY ../utils/pom.xml ../utils/
COPY ../utils/src ../utils/src

COPY pom.xml ./

RUN mvn -B dependency:go-offline -T 1C

COPY src ./src

RUN mvn -B clean install -DskipTests

FROM eclipse-temurin:17.0.10_7-jre-alpine

WORKDIR /app

COPY --from=build /app/module/target/*.jar ./app.jar

ENTRYPOINT ["java","-jar","/app/app.jar"]