spring:
  application:
    name: sender
  config:
    import: optional:configserver:http://localhost:8888

# DEFAULT CONFIGURATION FOR STARTUP WITHOUT CONFIG SERVER

application:
  title: sender
  version: 0.1
  config:
    request-mappings:
      sender: /api/send

server:
  port: 8092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    app: trace

