eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: api-gateway
  cloud:
    discovery:
      enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: contact
          uri: http://localhost:8090
          predicates:
            - Path=/api/contacts/**
        - id: notification
          uri: http://localhost:8091
          predicates:
            - Path=/api/notifications/**
        - id: sender
          uri: http://localhost:8092
          predicates:
            - Path=/api/send/**
        - id: security
          uri: http://localhost:8093
          predicates:
            - Path=/api/users/**, /api/security/**, /api/security-tg-users/**
        - id: telegram
          uri: http://localhost:8094
          predicates:
            - Path=/api/telegram/**

application:
  title: gateway
  version: 0.1
server:
  port: 8080

