host-ip: localhost
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${host-ip}:5432/postgres
    username: postgres
    password: 1234
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update