application:
  title: gateway
  version: 0.1
eureka:
  client:
    register-with-eureka: false

server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: contact
          uri: http://localhost:8090
          predicates:
            - Path=/api/contacts/**
        - id: notification
          uri: http://localhost:8091
          predicates:
            - Path=/api/notifications/**
        - id: send
          uri: http://localhost:8092
          predicates:
            - Path=/api/send/**
        - id: security
          uri: http://localhost:8093
          predicates:
            - Path=/api/users/**
            - Path=/api/security/**