eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8091
application:
  title: notification
  version: 1.0
  config:
    request-mappings:
      notification: /api/notifications

spring:
  application:
    name: notification
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ens
    username: postgres
    password: 1234
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
logging:
  level:
    app: trace
  file:
    path: \logs\
    name: notification.log

management:
  tracing:
    sampling:
      probability: 1.0
