application:
  title: security
  version: 0.1
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8093

spring:
  application:
    name: security
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ens
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    database: ens
    database-platform: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    app:
      security: trace