eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8092
application:
  title: sender
  version: 0.1
  config:
    contact:
      url: http://localhost:8090/api/contacts
    notification:
      url: http://localhost:8091/api/notifications

spring:
  application:
    name: sender
