eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8094
application:
  title: telegram
  version: 0.1
  config:
    contact:
      url: http://localhost:8080/api/contacts
    notification:
      url: http://localhost:8080/api/notifications

spring:
  application:
    name: telegram
logging:
  level:
    app:
      sender: trace