package app.telegram.users.model;

public enum InputState {
    BASE,
    REGISTRATION_USERNAME,
    REGISTRATION_PASSWORD,
    CONTACT_METHOD,
    CONTACT_CONTACT_ID,
    CONTACT_NOTIFICATION_NAME,
    NOTIFICATION_NAME,
    NOTIFICATION_TEXT
}
