package app.telegram.users.model;

public enum InputState {
    BASE,
    REGISTRATION_USERNAME,
    REGISTRATION_PASSWORD,
    REGISTRATION_FINISHED,
    CONTACT_METHOD,
    CONTACT_CONTACT_ID,
    CONTACT_NOTIFICATION_NAME,
    CONTACT_FINISHED,
    NOTIFICATION_NAME,
    NOTIFICATION_TEXT,
    NOTIFICATION_FINISHED
}
